import {
  Activity,
  Ambulance,
  Award,
  Baby,
  Bandage,
  Bone,
  Brain,
  Calendar,
  Clock,
  Dna,
  Eye,
  Flower2,
  Heart,
  HeartPulse,
  Home,
  Hospital,
  Leaf,
  Mail,
  MapPin,
  Microscope,
  Phone,
  Pill,
  Ribbon,
  ScanLine,
  ShieldCheck,
  Sparkles,
  Stethoscope,
  Syringe,
  UserRound,
  Users,
  type LucideIcon,
} from "lucide-react";

/** Keys map to Lucide components; fallback is UserRound. */
export const SERVICES_HIGHLIGHT_ICON_MAP: Record<string, LucideIcon> = {
  userRound: UserRound,
  pill: Pill,
  clock: Clock,
  brain: Brain,
  heart: Heart,
  stethoscope: Stethoscope,
  activity: Activity,
  sparkles: Sparkles,
  ambulance: Ambulance,
  hospital: Hospital,
  syringe: Syringe,
  bandage: Bandage,
  microscope: Microscope,
  eye: Eye,
  baby: Baby,
  bone: Bone,
  dna: Dna,
  scanLine: ScanLine,
  heartPulse: HeartPulse,
  phone: Phone,
  mail: Mail,
  mapPin: MapPin,
  shieldCheck: ShieldCheck,
  award: Award,
  users: Users,
  calendar: Calendar,
  home: Home,
  leaf: Leaf,
  ribbon: Ribbon,
  flower2: Flower2,
};

export const SERVICES_HIGHLIGHT_ICON_OPTIONS: { value: string; label: string }[] = [
  { value: "userRound", label: "User / person" },
  { value: "pill", label: "Pill / medicine" },
  { value: "clock", label: "Clock / time" },
  { value: "brain", label: "Brain / neurology" },
  { value: "heart", label: "Heart" },
  { value: "stethoscope", label: "Stethoscope" },
  { value: "activity", label: "Activity / pulse" },
  { value: "sparkles", label: "Sparkles" },
  { value: "ambulance", label: "Ambulance" },
  { value: "hospital", label: "Hospital" },
  { value: "syringe", label: "Syringe" },
  { value: "bandage", label: "Bandage / wound" },
  { value: "microscope", label: "Microscope / lab" },
  { value: "eye", label: "Eye / vision" },
  { value: "baby", label: "Baby / pediatric" },
  { value: "bone", label: "Bone / ortho" },
  { value: "dna", label: "DNA / genetics" },
  { value: "scanLine", label: "Scan / imaging" },
  { value: "heartPulse", label: "Heart pulse / cardio" },
  { value: "phone", label: "Phone" },
  { value: "mail", label: "Mail" },
  { value: "mapPin", label: "Location" },
  { value: "shieldCheck", label: "Shield / trust" },
  { value: "award", label: "Award / quality" },
  { value: "users", label: "People / team" },
  { value: "calendar", label: "Calendar" },
  { value: "home", label: "Home care" },
  { value: "leaf", label: "Leaf / wellness" },
  { value: "ribbon", label: "Ribbon / awareness" },
  { value: "flower2", label: "Flower / comfort" },
];

export function resolveServicesHighlightIcon(key: string): LucideIcon {
  return SERVICES_HIGHLIGHT_ICON_MAP[key] ?? UserRound;
}
